# Generated by Django 2.0.5 on 2018-05-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemytagline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagline',
            old_name='taglineObject',
            new_name='tagline',
        ),
    ]
