# Generated by Django 2.0.5 on 2018-05-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemytagline', '0002_auto_20180503_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvotes',
            name='taglineObject',
        ),
        migrations.RemoveField(
            model_name='upvotes',
            name='userObject',
        ),
        migrations.RemoveField(
            model_name='tagline',
            name='userObject',
        ),
        migrations.AddField(
            model_name='tagline',
            name='username',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.DeleteModel(
            name='upvotes',
        ),
        migrations.DeleteModel(
            name='userModel',
        ),
    ]
